move to version 0.0.58
eclipse/che-plugin-registry pull request #733
Opened 2020-12-03 03:36 UTC by johnsteele

Signed-off-by: John Steele <programjsteele@gmail.com>

### What does this PR do?

### Screenshot/screencast of this PR

### What issues does this PR fix or reference?

### How to test this PR?

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

2020-12-03 09:19 UTC, benoitf commented
@johnsteele could you please update as well https://github.com/eclipse/che-plugin-registry/blob/master/che-theia-plugins.yaml#L279-L304 
(we'll soon have only this file)

2020-12-10 19:37 UTC, ericwill requested changes
Please rebase and apply changes

2020-12-10 19:37 UTC, ericwill commented on v3/plugins/redhat/mta-vscode-extension/0.0.58/meta.yaml
>  apiVersion: v2
This change can be removed -- `meta.yaml` files are generated via the `che-theia-plugins.yaml` file now.

2020-12-10 19:37 UTC, ericwill commented on v3/plugins/redhat/mta-vscode-extension/latest.txt
> -0.0.56
This change can also be removed.

2020-12-10 19:37 UTC, ericwill commented on vscode-extensions.json
> +      "revision": "5ae3dd17a290b249fecea4a031b8debd71b5da24"
This change can also be removed, this file doesn't exist anymore (it's been replaced by `che-theia-plugins.yaml`)

2021-02-10 16:24 UTC, ericwill commented
Obsolete PR

2021-02-10 16:24 UTC, closed without merging